### ISSUE TITLE
Can't launch program correctly.

### ISSUE THREAD

**Issue by MountainThorn** [targor/JBLRecover#2]
When I launch JBL recover, it tells me "Could not find the correct speaker output, please select one manually." I click on "OK" and then the prompt disappears, and nothing else opens. When doing this again, it opens a new instance of JBL recover, as I can open up Task Manager and see like 8 instances open in the background.

I can't get into the actual setup.

**Comment by targor** [comment]
Please look in the right bottom corner at the status bar, there you can find a small symbol that looks like a shower ^^. Right click will exit the program, and a doubleclick will open the options menu for you, where you can select a proper device.

**Comment by MountainThorn** [comment]
Oh my goodness you are a genius. It's like you wrote the program or something. 

Thanks for the fix by the way. I use these for work and answer a lot of phones. The calls are pretty random though, so this headset would turn off before I get a call and then I can't hear the call coming in. You are literally a lifesaver.

**Comment by targor** [comment]
You are welcome :).

I have one of the JBL headsets for work too and because this shutdown functionality pissed me off so much, i wrote this program.
