### ISSUE TITLE
Headset turns off still

### ISSUE THREAD

**Issue by MountainThorn** [targor/JBLRecover#3]
Well I got the application opened up, but it doesn't seem to be working. I selected the audio device, and it shows the master volume as all the way up. It shows the track volume as about 1\8th. Plaback Signal volume seems to work when there is playback from the headphones. I have it set to 5 minutes.

Headset still turns off after about 10.

**Comment by MountainThorn** [comment]
In addition, I can set it to one minute and watch the playback signal go up every minute as intended. The headset turns off anyway. I am not sure if this is because the noise isn't loud enough or what.

**Comment by targor** [comment]
I added a boost option so the playback should be louder now. i also modified the playback values slightly.. test some minutes before using the boost, as the boost will dramatically increas the wav playback volume. even if the wav file is not hearable by human ears, it may cause issues on the human eardrum. i am no expert in this field.

I have updated the project, added a noplay modifier value and added a textfiled for manual editing if needed.
The new version also wont start twice now.

please try and check if it works better now.
https://github.com/targor/JBLRecover/releases/tag/Release_1.0.6

**Comment by MountainThorn** [comment]
Well you definitely made the program easier to use. Unfortunately it didn't seem to fix the problem though. The headset still powers down. The boost seems to work, technically. Windows detects sound being played for sure. I'm not really sure why my headset doesn't care and shuts down anyway.

**Comment by targor** [comment]
Which headset dou you have exactly? I can only say, that it works for mine. It is a JBL Quantum 800.

Maybe the frequency of the wav file is not recognized by your speaker.. i added more waves with other frequencies, eventually this will help. Caution. one of them is really hearable and one of them (15000 hz) maybe hearable by some people. I also normalized the waves with lufs, maybe the boost option must be enabled now. i need to test this with my headset too.

https://github.com/targor/JBLRecover/releases/tag/Release_1.0.7

**Comment by MountainThorn** [comment]
I am using the JBL Quantum 600.

I can actually hear the current one with the boost option on, though just barely. I will try some of the new options. Thanks so much for working on this with me by the way. I'm on my third headset at work and really don't want to bother my supervisor anymore about a fourth one haha.

**Comment by MountainThorn** [comment]
So I couldn't get the headset to stay on with any of those new sound files either. I could hear them coming out of the headset, but the headset would still turn off, the piece of junk.

So for now, I am just going to use it plugged in wired with an aux cable. It works fine, I just don't get the RGB or the benefit of it being wireless.

If you continue to update your program, I will gladly try the new versions. For now though I have a solution, even if it isn't perfect. If you don't want to worry about it then you really shouldn't. Thanks for all the help.
