### ISSUE TITLE
Program Doesn't work, on boot runs for 3 seconds and thats it

### ISSUE THREAD

**Issue by Wontell** [targor/JBLRecover#4]
Hello,
The program doesn't work, when i boot it runs for like 3 seconds and stops playing
Also it doesn't detect my JBL800 headphones, every time i load it it says "not detected, selecting default device"
The only way to make it "work" is to write 10 times the number 9 in the time field, it starts to work and after 5 seconds hangs, completely and have to be killed from the task manager

![01](https://user-images.githubusercontent.com/36778216/192123776-62ca0e61-7d08-461d-809d-ccbcf6138cc8.jpg)
![02](https://user-images.githubusercontent.com/36778216/192123777-4c341649-3e22-41e5-b6c7-521bf796c852.jpg)
![03](https://user-images.githubusercontent.com/36778216/192123778-cc70b8e2-6826-4ae3-9d35-5df2aee72ab1.jpg)

**Comment by targor** [comment]
The wav (loop)playtime in minutes field is used to decide in which interval the wav should be played. If you set this time higher, then the wav will play every 999999.... minutes. to play the wav more often, set it to a smaller value e.g. 3 minutes.

That the wav only plays 3 Seconds is intended, as the sound is set to a high volume and the playtime should be as short as possible to not harm your eardrum even if the soundfile may not be hearable.

**Comment by Wontell** [comment]
you right, i tested it longer and it works, but for some reason i need to set the timer shorter, 9 minutes too long
Also i noticed that with ANC on Auto-OFF is shorter vs with ANC off
Before that i would play a fart Noice every 60 second using play list and surprisingly it wouldn't work, even if it was loud
Your files do work, even without your software using play list on loop, you have one should that cant be heard by humans and it works playing on loop.
But now i re-tested your software and its the best solution, I had no issues for a full day

Maybe You can upload it for free to Windows store and you'll get more downloads, it will be easy to find and download and update from inside windows.
Its a nice software and im sure people with other brands can use it
